server:
  port: ${PORT:5000}

base-url: /api

logging:
  level:
    root: INFO

spring:
  application:
    name: taskManager

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  liquibase:
#    change-log: classpath:db/changelog/changelog-master.xml
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  swagger-ui:
    path: /swagger-ui.html