spring:
  jpa:
    show-sql: true

  datasource:
    url: jdbc:h2:./taskdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

logging:
  level:
    root: DEBUG