server:
  port: ${PORT:5000}

base-url: /api

logging:
  level:
    root: INFO

spring:
  application:
    name: taskManager

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: jdbc:h2:./taskdb
    username: sa
    password:

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

